name: Auto Minify JS and CSS Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'includes/Admin/assets/**/*.js'
      - 'includes/Admin/assets/**/*.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node tools
        run: |
          npm install -g terser clean-css-cli

      - name: Minify JS files
        run: |
          find includes/Admin/assets -type f -name "*.js" \
            ! -name "*.min.js" \
            ! -path "*/build/*" \
            ! -name "webpack.config.js" \
            ! -name ".eslintrc.js" \
            -exec bash -c 'terser "$0" -o "${0%.js}.min.js" --compress --mangle' {} \;

      - name: Minify CSS files
        run: |
          find includes/Admin/assets -type f -name "*.css" \
            ! -name "*.min.css" \
            ! -path "*/build/*" \
            -exec bash -c 'cleancss -o "${0%.css}.min.css" "$0"' {} \;

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate minified JS and CSS files"
